title: "Remote theme example"
remote_theme: just-the-docs/just-the-docs
color_scheme: nqo

# Site search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
